import Head from 'next/head'
import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import PostCard from '../components/PostCard'
import axios from 'axios';

export default function Home({posts}) {
  const [hydrated, setHydrated] = useState(false);
  useEffect(() => {
        setHydrated(true);
    }, []);
    if (!hydrated) {
        return null;
    }
  return (
    <>
    <Head>
    <title>NT,HE</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main className='s-content'>
     <div className='hero'>
       <h1>No Thoughts, Head Empty.</h1>
     </div>
     <div className='row masonry-wap'>
      <h2>Recent Posts</h2>
      <motion.div initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{
            delay: 0.75,
            duration: 0.2,
        }} className='archive'>
        
        {posts?.length < 1 ? 'No posts' : posts?.map(post=> <PostCard key={post._id} post={post}/>)}
      </motion.div>
     </div>
  </main>
</>
  )
}
export const getServerSideProps = async()=>{
  let hostname;
  if(process.env.NODE_ENV === 'development'){
    hostname = process.env.NEXT_PUBLIC_DEV_URL
  }else{
    hostname = process.env.NEXT_PUBLIC_PROD_URL
  };
  const post = await axios.get(`http://${hostname}/api/posts/recentposts`);
  return({
    props:{
      posts:post.data
    }
  })
}
